export default {
  photo: {
    0: "1.",
    1: "2.",
    2: "3.",
    3: "4.",
    4: "5.",
    5: "6.",
    6: "7.",
    7: "8.",
    8: "9.",
    9: "10.",
    10: "11.",
  },
  floor: {
    0.5: "medzi prízemím a 1. poschodím",
    1.0: "na 1. poschodí",
    1.5: "medzi 1. a 2. poschodím",
    2.0: "na 2. poschodí",
    2.5: "medzi 2. a 3. poschodím",
    3.0: "na 3. poschodí",
    3.5: "medzi 3. a 4. poschodím",
    4.0: "na 4. poschodí",
  },
  side: {
    z: "základka",
    s: "stred",
    g: "gymnázium",
  },
  age: {
    11: 11,
    12: 12,
    13: 13,
    14: 14,
    15: 15,
    16: 16,
    17: 17,
    18: 18,
    19: 19,
  },
  yearsAtSchool: {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
    11: 11,
    12: 12,
    13: 13,
  },
  local: {
    all: "na rovnakom poschodí aj strane",
    side: "na rovnakej strane, ale inom poschodí",
    floor: "nba rovnakom poschodí, ale opačnej strane",
    none: "na inom poschodí aj strane",
  },
  seen: {
    0: "určite áno",
    1: "skôr áno",
    2: "skôr nie",
    3: "určite nie",
  },
  correct: {
    all: "poschodie aj strana",
    side: "iba strana",
    floor: "iba poschodie",
    none: "ani strana, ani poschodie",
  },
  guessedFloor: {
    0.5: "medzi prízemím a 1. poschodím",
    1.0: "na 1. poschodí",
    1.5: "medzi 1. a 2. poschodím",
    2.0: "na 2. poschodí",
    2.5: "medzi 2. a 3. poschodím",
    3.0: "na 3. poschodí",
    3.5: "medzi 3. a 4. poschodím",
    4.0: "na 4. poschodí",
  },
  guessedSide: {
    z: "základka",
    s: "stred",
    g: "gymnázium",
  },
};
